/* eslint-disable */
// AUTO-GENERATED by scripts/sync-react-bits.mjs — do not edit manually
// Server-safe metadata only (no component imports).

export interface ReactBitsMetaEntry {
  slug: string;
  title: string;
  sourceFile: string;
}

export const REACT_BITS_META: Record<string, ReactBitsMetaEntry> = {
  "AnimatedContent-TS-TW": {
    slug: "AnimatedContent-TS-TW",
    title: "AnimatedContent",
    sourceFile: "AnimatedContent.tsx",
  },
  "AnimatedList-TS-TW": {
    slug: "AnimatedList-TS-TW",
    title: "AnimatedList",
    sourceFile: "AnimatedList.tsx",
  },
  "Antigravity-TS-TW": {
    slug: "Antigravity-TS-TW",
    title: "Antigravity",
    sourceFile: "Antigravity.tsx",
  },
  "ASCIIText-TS-TW": {
    slug: "ASCIIText-TS-TW",
    title: "ASCIIText",
    sourceFile: "ASCIIText.tsx",
  },
  "Aurora-TS-TW": {
    slug: "Aurora-TS-TW",
    title: "Aurora",
    sourceFile: "Aurora.tsx",
  },
  "Balatro-TS-TW": {
    slug: "Balatro-TS-TW",
    title: "Balatro",
    sourceFile: "Balatro.tsx",
  },
  "Ballpit-TS-TW": {
    slug: "Ballpit-TS-TW",
    title: "Ballpit",
    sourceFile: "Ballpit.tsx",
  },
  "Beams-TS-TW": {
    slug: "Beams-TS-TW",
    title: "Beams",
    sourceFile: "Beams.tsx",
  },
  "BlobCursor-TS-TW": {
    slug: "BlobCursor-TS-TW",
    title: "BlobCursor",
    sourceFile: "BlobCursor.tsx",
  },
  "BlurText-TS-TW": {
    slug: "BlurText-TS-TW",
    title: "BlurText",
    sourceFile: "BlurText.tsx",
  },
  "BorderGlow-TS-TW": {
    slug: "BorderGlow-TS-TW",
    title: "BorderGlow",
    sourceFile: "BorderGlow.tsx",
  },
  "BounceCards-TS-TW": {
    slug: "BounceCards-TS-TW",
    title: "BounceCards",
    sourceFile: "BounceCards.tsx",
  },
  "BubbleMenu-TS-TW": {
    slug: "BubbleMenu-TS-TW",
    title: "BubbleMenu",
    sourceFile: "BubbleMenu.tsx",
  },
  "CardNav-TS-TW": {
    slug: "CardNav-TS-TW",
    title: "CardNav",
    sourceFile: "CardNav.tsx",
  },
  "CardSwap-TS-TW": {
    slug: "CardSwap-TS-TW",
    title: "CardSwap",
    sourceFile: "CardSwap.tsx",
  },
  "Carousel-TS-TW": {
    slug: "Carousel-TS-TW",
    title: "Carousel",
    sourceFile: "Carousel.tsx",
  },
  "ChromaGrid-TS-TW": {
    slug: "ChromaGrid-TS-TW",
    title: "ChromaGrid",
    sourceFile: "ChromaGrid.tsx",
  },
  "CircularGallery-TS-TW": {
    slug: "CircularGallery-TS-TW",
    title: "CircularGallery",
    sourceFile: "CircularGallery.tsx",
  },
  "CircularText-TS-TW": {
    slug: "CircularText-TS-TW",
    title: "CircularText",
    sourceFile: "CircularText.tsx",
  },
  "ClickSpark-TS-TW": {
    slug: "ClickSpark-TS-TW",
    title: "ClickSpark",
    sourceFile: "ClickSpark.tsx",
  },
  "ColorBends-TS-TW": {
    slug: "ColorBends-TS-TW",
    title: "ColorBends",
    sourceFile: "ColorBends.tsx",
  },
  "Counter-TS-TW": {
    slug: "Counter-TS-TW",
    title: "Counter",
    sourceFile: "Counter.tsx",
  },
  "CountUp-TS-TW": {
    slug: "CountUp-TS-TW",
    title: "CountUp",
    sourceFile: "CountUp.tsx",
  },
  "Crosshair-TS-TW": {
    slug: "Crosshair-TS-TW",
    title: "Crosshair",
    sourceFile: "Crosshair.tsx",
  },
  "Cubes-TS-TW": {
    slug: "Cubes-TS-TW",
    title: "Cubes",
    sourceFile: "Cubes.tsx",
  },
  "CurvedLoop-TS-TW": {
    slug: "CurvedLoop-TS-TW",
    title: "CurvedLoop",
    sourceFile: "CurvedLoop.tsx",
  },
  "DarkVeil-TS-TW": {
    slug: "DarkVeil-TS-TW",
    title: "DarkVeil",
    sourceFile: "DarkVeil.tsx",
  },
  "DecayCard-TS-TW": {
    slug: "DecayCard-TS-TW",
    title: "DecayCard",
    sourceFile: "DecayCard.tsx",
  },
  "DecryptedText-TS-TW": {
    slug: "DecryptedText-TS-TW",
    title: "DecryptedText",
    sourceFile: "DecryptedText.tsx",
  },
  "Dither-TS-TW": {
    slug: "Dither-TS-TW",
    title: "Dither",
    sourceFile: "Dither.tsx",
  },
  "Dock-TS-TW": {
    slug: "Dock-TS-TW",
    title: "Dock",
    sourceFile: "Dock.tsx",
  },
  "DomeGallery-TS-TW": {
    slug: "DomeGallery-TS-TW",
    title: "DomeGallery",
    sourceFile: "DomeGallery.tsx",
  },
  "DotField-TS-TW": {
    slug: "DotField-TS-TW",
    title: "DotField",
    sourceFile: "DotField.tsx",
  },
  "DotGrid-TS-TW": {
    slug: "DotGrid-TS-TW",
    title: "DotGrid",
    sourceFile: "DotGrid.tsx",
  },
  "ElasticSlider-TS-TW": {
    slug: "ElasticSlider-TS-TW",
    title: "ElasticSlider",
    sourceFile: "ElasticSlider.tsx",
  },
  "ElectricBorder-TS-TW": {
    slug: "ElectricBorder-TS-TW",
    title: "ElectricBorder",
    sourceFile: "ElectricBorder.tsx",
  },
  "EvilEye-TS-TW": {
    slug: "EvilEye-TS-TW",
    title: "EvilEye",
    sourceFile: "EvilEye.tsx",
  },
  "FadeContent-TS-TW": {
    slug: "FadeContent-TS-TW",
    title: "FadeContent",
    sourceFile: "FadeContent.tsx",
  },
  "FallingText-TS-TW": {
    slug: "FallingText-TS-TW",
    title: "FallingText",
    sourceFile: "FallingText.tsx",
  },
  "FaultyTerminal-TS-TW": {
    slug: "FaultyTerminal-TS-TW",
    title: "FaultyTerminal",
    sourceFile: "FaultyTerminal.tsx",
  },
  "Ferrofluid-TS-TW": {
    slug: "Ferrofluid-TS-TW",
    title: "Ferrofluid",
    sourceFile: "Ferrofluid.tsx",
  },
  "FloatingLines-TS-TW": {
    slug: "FloatingLines-TS-TW",
    title: "FloatingLines",
    sourceFile: "FloatingLines.tsx",
  },
  "FlowingMenu-TS-TW": {
    slug: "FlowingMenu-TS-TW",
    title: "FlowingMenu",
    sourceFile: "FlowingMenu.tsx",
  },
  "FluidGlass-TS-TW": {
    slug: "FluidGlass-TS-TW",
    title: "FluidGlass",
    sourceFile: "FluidGlass.tsx",
  },
  "FlyingPosters-TS-TW": {
    slug: "FlyingPosters-TS-TW",
    title: "FlyingPosters",
    sourceFile: "FlyingPosters.tsx",
  },
  "Folder-TS-TW": {
    slug: "Folder-TS-TW",
    title: "Folder",
    sourceFile: "Folder.tsx",
  },
  "FuzzyText-TS-TW": {
    slug: "FuzzyText-TS-TW",
    title: "FuzzyText",
    sourceFile: "FuzzyText.tsx",
  },
  "Galaxy-TS-TW": {
    slug: "Galaxy-TS-TW",
    title: "Galaxy",
    sourceFile: "Galaxy.tsx",
  },
  "GhostCursor-TS-TW": {
    slug: "GhostCursor-TS-TW",
    title: "GhostCursor",
    sourceFile: "GhostCursor.tsx",
  },
  "GlareHover-TS-TW": {
    slug: "GlareHover-TS-TW",
    title: "GlareHover",
    sourceFile: "GlareHover.tsx",
  },
  "GlassIcons-TS-TW": {
    slug: "GlassIcons-TS-TW",
    title: "GlassIcons",
    sourceFile: "GlassIcons.tsx",
  },
  "GlassSurface-TS-TW": {
    slug: "GlassSurface-TS-TW",
    title: "GlassSurface",
    sourceFile: "GlassSurface.tsx",
  },
  "GlitchText-TS-TW": {
    slug: "GlitchText-TS-TW",
    title: "GlitchText",
    sourceFile: "GlitchText.tsx",
  },
  "GooeyNav-TS-TW": {
    slug: "GooeyNav-TS-TW",
    title: "GooeyNav",
    sourceFile: "GooeyNav.tsx",
  },
  "GradientBlinds-TS-TW": {
    slug: "GradientBlinds-TS-TW",
    title: "GradientBlinds",
    sourceFile: "GradientBlinds.tsx",
  },
  "GradientText-TS-TW": {
    slug: "GradientText-TS-TW",
    title: "GradientText",
    sourceFile: "GradientText.tsx",
  },
  "GradualBlur-TS-TW": {
    slug: "GradualBlur-TS-TW",
    title: "GradualBlur",
    sourceFile: "GradualBlur.tsx",
  },
  "Grainient-TS-TW": {
    slug: "Grainient-TS-TW",
    title: "Grainient",
    sourceFile: "Grainient.tsx",
  },
  "GridDistortion-TS-TW": {
    slug: "GridDistortion-TS-TW",
    title: "GridDistortion",
    sourceFile: "GridDistortion.tsx",
  },
  "GridMotion-TS-TW": {
    slug: "GridMotion-TS-TW",
    title: "GridMotion",
    sourceFile: "GridMotion.tsx",
  },
  "GridScan-TS-TW": {
    slug: "GridScan-TS-TW",
    title: "GridScan",
    sourceFile: "GridScan.tsx",
  },
  "Hyperspeed-TS-TW": {
    slug: "Hyperspeed-TS-TW",
    title: "Hyperspeed",
    sourceFile: "Hyperspeed.tsx",
  },
  "ImageTrail-TS-TW": {
    slug: "ImageTrail-TS-TW",
    title: "ImageTrail",
    sourceFile: "ImageTrail.tsx",
  },
  "InfiniteMenu-TS-TW": {
    slug: "InfiniteMenu-TS-TW",
    title: "InfiniteMenu",
    sourceFile: "InfiniteMenu.tsx",
  },
  "Iridescence-TS-TW": {
    slug: "Iridescence-TS-TW",
    title: "Iridescence",
    sourceFile: "Iridescence.tsx",
  },
  "Lanyard-TS-TW": {
    slug: "Lanyard-TS-TW",
    title: "Lanyard",
    sourceFile: "Lanyard.tsx",
  },
  "LaserFlow-TS-TW": {
    slug: "LaserFlow-TS-TW",
    title: "LaserFlow",
    sourceFile: "LaserFlow.tsx",
  },
  "LetterGlitch-TS-TW": {
    slug: "LetterGlitch-TS-TW",
    title: "LetterGlitch",
    sourceFile: "LetterGlitch.tsx",
  },
  "Lightfall-TS-TW": {
    slug: "Lightfall-TS-TW",
    title: "Lightfall",
    sourceFile: "Lightfall.tsx",
  },
  "Lightning-TS-TW": {
    slug: "Lightning-TS-TW",
    title: "Lightning",
    sourceFile: "Lightning.tsx",
  },
  "LightPillar-TS-TW": {
    slug: "LightPillar-TS-TW",
    title: "LightPillar",
    sourceFile: "LightPillar.tsx",
  },
  "LightRays-TS-TW": {
    slug: "LightRays-TS-TW",
    title: "LightRays",
    sourceFile: "LightRays.tsx",
  },
  "LineWaves-TS-TW": {
    slug: "LineWaves-TS-TW",
    title: "LineWaves",
    sourceFile: "LineWaves.tsx",
  },
  "LiquidChrome-TS-TW": {
    slug: "LiquidChrome-TS-TW",
    title: "LiquidChrome",
    sourceFile: "LiquidChrome.tsx",
  },
  "LiquidEther-TS-TW": {
    slug: "LiquidEther-TS-TW",
    title: "LiquidEther",
    sourceFile: "LiquidEther.tsx",
  },
  "LogoLoop-TS-TW": {
    slug: "LogoLoop-TS-TW",
    title: "LogoLoop",
    sourceFile: "LogoLoop.tsx",
  },
  "MagicBento-TS-TW": {
    slug: "MagicBento-TS-TW",
    title: "MagicBento",
    sourceFile: "MagicBento.tsx",
  },
  "MagicRings-TS-TW": {
    slug: "MagicRings-TS-TW",
    title: "MagicRings",
    sourceFile: "MagicRings.tsx",
  },
  "Magnet-TS-TW": {
    slug: "Magnet-TS-TW",
    title: "Magnet",
    sourceFile: "Magnet.tsx",
  },
  "MagnetLines-TS-TW": {
    slug: "MagnetLines-TS-TW",
    title: "MagnetLines",
    sourceFile: "MagnetLines.tsx",
  },
  "Masonry-TS-TW": {
    slug: "Masonry-TS-TW",
    title: "Masonry",
    sourceFile: "Masonry.tsx",
  },
  "MetaBalls-TS-TW": {
    slug: "MetaBalls-TS-TW",
    title: "MetaBalls",
    sourceFile: "MetaBalls.tsx",
  },
  "MetallicPaint-TS-TW": {
    slug: "MetallicPaint-TS-TW",
    title: "MetallicPaint",
    sourceFile: "MetallicPaint.tsx",
  },
  "ModelViewer-TS-TW": {
    slug: "ModelViewer-TS-TW",
    title: "ModelViewer",
    sourceFile: "ModelViewer.tsx",
  },
  "Noise-TS-TW": {
    slug: "Noise-TS-TW",
    title: "Noise",
    sourceFile: "Noise.tsx",
  },
  "Orb-TS-TW": {
    slug: "Orb-TS-TW",
    title: "Orb",
    sourceFile: "Orb.tsx",
  },
  "OrbitImages-TS-TW": {
    slug: "OrbitImages-TS-TW",
    title: "OrbitImages",
    sourceFile: "OrbitImages.tsx",
  },
  "Particles-TS-TW": {
    slug: "Particles-TS-TW",
    title: "Particles",
    sourceFile: "Particles.tsx",
  },
  "PillNav-TS-TW": {
    slug: "PillNav-TS-TW",
    title: "PillNav",
    sourceFile: "PillNav.tsx",
  },
  "PixelBlast-TS-TW": {
    slug: "PixelBlast-TS-TW",
    title: "PixelBlast",
    sourceFile: "PixelBlast.tsx",
  },
  "PixelCard-TS-TW": {
    slug: "PixelCard-TS-TW",
    title: "PixelCard",
    sourceFile: "PixelCard.tsx",
  },
  "PixelSnow-TS-TW": {
    slug: "PixelSnow-TS-TW",
    title: "PixelSnow",
    sourceFile: "PixelSnow.tsx",
  },
  "PixelTrail-TS-TW": {
    slug: "PixelTrail-TS-TW",
    title: "PixelTrail",
    sourceFile: "PixelTrail.tsx",
  },
  "PixelTransition-TS-TW": {
    slug: "PixelTransition-TS-TW",
    title: "PixelTransition",
    sourceFile: "PixelTransition.tsx",
  },
  "Plasma-TS-TW": {
    slug: "Plasma-TS-TW",
    title: "Plasma",
    sourceFile: "Plasma.tsx",
  },
  "PlasmaWave-TS-TW": {
    slug: "PlasmaWave-TS-TW",
    title: "PlasmaWave",
    sourceFile: "PlasmaWave.tsx",
  },
  "Prism-TS-TW": {
    slug: "Prism-TS-TW",
    title: "Prism",
    sourceFile: "Prism.tsx",
  },
  "PrismaticBurst-TS-TW": {
    slug: "PrismaticBurst-TS-TW",
    title: "PrismaticBurst",
    sourceFile: "PrismaticBurst.tsx",
  },
  "ProfileCard-TS-TW": {
    slug: "ProfileCard-TS-TW",
    title: "ProfileCard",
    sourceFile: "ProfileCard.tsx",
  },
  "Radar-TS-TW": {
    slug: "Radar-TS-TW",
    title: "Radar",
    sourceFile: "Radar.tsx",
  },
  "ReflectiveCard-TS-TW": {
    slug: "ReflectiveCard-TS-TW",
    title: "ReflectiveCard",
    sourceFile: "ReflectiveCard.tsx",
  },
  "Ribbons-TS-TW": {
    slug: "Ribbons-TS-TW",
    title: "Ribbons",
    sourceFile: "Ribbons.tsx",
  },
  "RippleGrid-TS-TW": {
    slug: "RippleGrid-TS-TW",
    title: "RippleGrid",
    sourceFile: "RippleGrid.tsx",
  },
  "RotatingText-TS-TW": {
    slug: "RotatingText-TS-TW",
    title: "RotatingText",
    sourceFile: "RotatingText.tsx",
  },
  "ScrambledText-TS-TW": {
    slug: "ScrambledText-TS-TW",
    title: "ScrambledText",
    sourceFile: "ScrambledText.tsx",
  },
  "ScrollFloat-TS-TW": {
    slug: "ScrollFloat-TS-TW",
    title: "ScrollFloat",
    sourceFile: "ScrollFloat.tsx",
  },
  "ScrollReveal-TS-TW": {
    slug: "ScrollReveal-TS-TW",
    title: "ScrollReveal",
    sourceFile: "ScrollReveal.tsx",
  },
  "ScrollStack-TS-TW": {
    slug: "ScrollStack-TS-TW",
    title: "ScrollStack",
    sourceFile: "ScrollStack.tsx",
  },
  "ScrollVelocity-TS-TW": {
    slug: "ScrollVelocity-TS-TW",
    title: "ScrollVelocity",
    sourceFile: "ScrollVelocity.tsx",
  },
  "ShapeBlur-TS-TW": {
    slug: "ShapeBlur-TS-TW",
    title: "ShapeBlur",
    sourceFile: "ShapeBlur.tsx",
  },
  "ShapeGrid-TS-TW": {
    slug: "ShapeGrid-TS-TW",
    title: "ShapeGrid",
    sourceFile: "ShapeGrid.tsx",
  },
  "ShinyText-TS-TW": {
    slug: "ShinyText-TS-TW",
    title: "ShinyText",
    sourceFile: "ShinyText.tsx",
  },
  "Shuffle-TS-TW": {
    slug: "Shuffle-TS-TW",
    title: "Shuffle",
    sourceFile: "Shuffle.tsx",
  },
  "SideRays-TS-TW": {
    slug: "SideRays-TS-TW",
    title: "SideRays",
    sourceFile: "SideRays.tsx",
  },
  "Silk-TS-TW": {
    slug: "Silk-TS-TW",
    title: "Silk",
    sourceFile: "Silk.tsx",
  },
  "SoftAurora-TS-TW": {
    slug: "SoftAurora-TS-TW",
    title: "SoftAurora",
    sourceFile: "SoftAurora.tsx",
  },
  "SplashCursor-TS-TW": {
    slug: "SplashCursor-TS-TW",
    title: "SplashCursor",
    sourceFile: "SplashCursor.tsx",
  },
  "SplitText-TS-TW": {
    slug: "SplitText-TS-TW",
    title: "SplitText",
    sourceFile: "SplitText.tsx",
  },
  "SpotlightCard-TS-TW": {
    slug: "SpotlightCard-TS-TW",
    title: "SpotlightCard",
    sourceFile: "SpotlightCard.tsx",
  },
  "Stack-TS-TW": {
    slug: "Stack-TS-TW",
    title: "Stack",
    sourceFile: "Stack.tsx",
  },
  "StaggeredMenu-TS-TW": {
    slug: "StaggeredMenu-TS-TW",
    title: "StaggeredMenu",
    sourceFile: "StaggeredMenu.tsx",
  },
  "StarBorder-TS-TW": {
    slug: "StarBorder-TS-TW",
    title: "StarBorder",
    sourceFile: "StarBorder.tsx",
  },
  "Stepper-TS-TW": {
    slug: "Stepper-TS-TW",
    title: "Stepper",
    sourceFile: "Stepper.tsx",
  },
  "StickerPeel-TS-TW": {
    slug: "StickerPeel-TS-TW",
    title: "StickerPeel",
    sourceFile: "StickerPeel.tsx",
  },
  "Strands-TS-TW": {
    slug: "Strands-TS-TW",
    title: "Strands",
    sourceFile: "Strands.tsx",
  },
  "TargetCursor-TS-TW": {
    slug: "TargetCursor-TS-TW",
    title: "TargetCursor",
    sourceFile: "TargetCursor.tsx",
  },
  "TextCursor-TS-TW": {
    slug: "TextCursor-TS-TW",
    title: "TextCursor",
    sourceFile: "TextCursor.tsx",
  },
  "TextPressure-TS-TW": {
    slug: "TextPressure-TS-TW",
    title: "TextPressure",
    sourceFile: "TextPressure.tsx",
  },
  "TextType-TS-TW": {
    slug: "TextType-TS-TW",
    title: "TextType",
    sourceFile: "TextType.tsx",
  },
  "Threads-TS-TW": {
    slug: "Threads-TS-TW",
    title: "Threads",
    sourceFile: "Threads.tsx",
  },
  "TiltedCard-TS-TW": {
    slug: "TiltedCard-TS-TW",
    title: "TiltedCard",
    sourceFile: "TiltedCard.tsx",
  },
  "TrueFocus-TS-TW": {
    slug: "TrueFocus-TS-TW",
    title: "TrueFocus",
    sourceFile: "TrueFocus.tsx",
  },
  "VariableProximity-TS-TW": {
    slug: "VariableProximity-TS-TW",
    title: "VariableProximity",
    sourceFile: "VariableProximity.tsx",
  },
  "Waves-TS-TW": {
    slug: "Waves-TS-TW",
    title: "Waves",
    sourceFile: "Waves.tsx",
  },
};

export function getReactBitsMeta(slug: string): ReactBitsMetaEntry | undefined {
  return REACT_BITS_META[slug];
}
